### PR TITLE
Pull version from single SoT (`main.go`)

### PR DESCRIPTION
**Pull request by mmonaco**
*This might be helpful, no worries otherwise :)*

This could go the other way around too, stamping it in with `-ldflags='-X appVersion=$(VERSION)'`

### CODE REVIEW

**Comment by maximbaz** [comment]
Thanks! I think I most often saw others use the alternative `-ldflags` way, let's do it that way!

**Comment by mmonaco** [comment]
> Thanks! I think I most often saw others use the alternative `-ldflags` way, let's do it that way!

Sure, will do.

The difference is whether you only want a version to come from the build system so that you'd get something like:

```
$ go run main.go --version
YubiKey touch detector version: <UNDEFINED>
```

**Comment by maximbaz** [comment]
Hmmm very good point, sorry allow me to change my mind, let's go with your current version :sweat_smile:

**Comment by maximbaz** [comment]
Would there be any downsides with the simpler `sed` command like the one I pushed?

**Comment by mmonaco** [comment]
> Would there be any downsides with the simpler `sed` command like the one I pushed?

Not really. The main difference is that I was trying to be flexible with

```
const appVersion =
```

vs

```
const (
  appVersion = ...
)
```

**Comment by maximbaz** [comment]
OK I'll be mindful about it, thanks!

**Comment by mmonaco** [comment]
OOC, unrelated, why do you vendor the deps like this? I think this is meant for checking in the deps. If you're going to .gitignore the vendor dir, why not let the default go pkg cache be used?

**Comment by maximbaz** [comment]
I add a tarball with vendored dependencies to the release only because some distros build (or prefer to build) offline, which is a problem if they need to allow internet to run `go get`. 

I haven't been using Makefile for local development for a while, I suppose it's not correct that my `local` target depends on `vendor`, it shouldn't. Was this the part that made you ask about it?

**Comment by mmonaco** [comment]
Ah, that make sense! Yeah I saw it show up when I did `make run`.

I guess you could have:

```
.PHONY: run
run: build
        ./$(BIN)
```

and drop `local` altogether

**Comment by maximbaz** [comment]
Agree, just pushed :+1:

**Comment by maximbaz** [comment]
@mmonaco check this out! https://github.com/maximbaz/yubikey-touch-detector/commit/b70e029ab8c92635739bc3724c6aaad3e29a367c

https://whynothugo.nl/journal/2024/12/16/injecting-project-versions-into-builds/

Well now it's a true single source of truth! Sending big thanks to @WhyNotHugo :grin: :clap:

**Comment by mmonaco** [comment]
Cool, thanks for the follow up :) I didn't know the `.gitattributes` trick. You might want to use the `git describe --match <pattern>`  just in case you do a misc tag some day. I think I've seen this issue with git PKGBUILDs before.

**Comment by WhyNotHugo** [comment]
With the above approach, builds from a git checkout try to determine the version at runtime, so the binaries will fail to run if the current working directory is not a git repository.

I tried to make a version that fully resolves things at compile time. It works for tarballs, but not a on a git-checkout, because of how Makefile requires escaping `$`:

```diff
commit fcf429ce78ddf997016d7852beef6521b860f528
Author: Hugo Osvaldo Barrera <hugo@whynothugo.nl>
Date:   Thu Jan 9 03:24:55 2025 +0100

    Determine version at compile time
    
    The current implementation injects the version into tarballs, and leaves
    the placeholder string in-place when building from a git checkout. When
    building from a git checkout, and the version is determined by running
    `git-describe` at runtime.
    
    If the binary is executed from a different path, `git-describe` will
    yield bogus output (or fail; this depends on the current directory).
    
    Resolve the real version at compile time, and inject this into the
    build, even when building from a git checkout.

diff --git a/.gitattributes b/.gitattributes
index b3f4c20..234b702 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1 +1 @@
-/main.go export-subst
+/Makefile export-subst
diff --git a/Makefile b/Makefile
index 1584000..e6b9838 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,11 @@
 BIN := yubikey-touch-detector
-VERSION := $(shell git describe --tags)
+# This value replaced by git-archive.
+VERSION := "$Format:%(describe)$"
+
+# If no replacement happened, use version from git-describe.
+ifneq (,$(findstring Format,$(VERSION)))
+    VERSION := $(shell git describe --tags 2>/dev/null || echo "unknown")
+endif
 
 PREFIX ?= /usr
 LIB_DIR = $(DESTDIR)$(PREFIX)/lib
@@ -18,7 +24,7 @@ run: build
 
 .PHONY: build
 build: main.go detector/ notifier/ yubikey-touch-detector.1
-	go build -o $(BIN) main.go
+	go build -ldflags "-X main.Version=$(VERSION)" -o $(BIN) main.go
 
 yubikey-touch-detector.1: yubikey-touch-detector.1.scd
 	scdoc < '$<' > '$@'
@@ -56,3 +62,7 @@ install:
 	install -Dm644 -t "$(SHARE_DIR)/doc/$(BIN)/" README.md
 	install -Dm644 -t "$(SHARE_DIR)/doc/$(BIN)/" service.conf.example
 	install -Dm644 -t "$(SHARE_DIR)/man/man1/" yubikey-touch-detector.1
+
+.PHONY: print-version
+print-version:
+	@echo $(VERSION)
diff --git a/main.go b/main.go
index 3c20616..39f783c 100644
--- a/main.go
+++ b/main.go
@@ -4,7 +4,6 @@ import (
 	"flag"
 	"fmt"
 	"os"
-	"os/exec"
 	"os/signal"
 	"path"
 	"path/filepath"
@@ -19,6 +18,8 @@ import (
 	"github.com/maximbaz/yubikey-touch-detector/notifier"
 )
 
+var Version = "undefined"
+
 func main() {
 	truthyValues := map[string]bool{"true": true, "yes": true, "1": true}
 
@@ -41,7 +42,7 @@ func main() {
 	flag.Parse()
 
 	if version {
-		fmt.Println("YubiKey touch detector version:", appVersion())
+		fmt.Println("YubiKey touch detector version:", Version)
 		os.Exit(0)
 	}
 
@@ -151,15 +152,3 @@ func setupExitSignalWatch(exits *sync.Map) {
 	log.Debug("Stopping YubiKey touch detector")
 	os.Exit(0)
 }
-
-func appVersion() string {
-	version := "$Format:%(describe)$"
-	if strings.HasPrefix(version, "$") {
-		out, err := exec.Command("git", "describe", "--tags").Output()
-		if err != nil {
-			panic(fmt.Sprintf("Failed to determine version using 'git describe': %v", err))
-		}
-		version = strings.TrimSpace(string(out))
-	}
-	return version
-}
```

I think the solution might be to use a txt file with `export-subst`, and read from that in the Makefile.

**Comment by maximbaz** [comment]
I see! At first I was sold on the idea to fully resolve version at compile time, but after playing around a bit with your patch, I became a bit in doubt whether it's beneficial to sacrifice freedom of choice of how to compile app... There are obviously pros and cons with every approach, but I'm very curious to hear what you think about the below:

In theory one can get the sources either by `git clone`-ing (implying you have `git`) or by downloading tarball (which already includes version thanks to `git archive`). So to get into an issue, you have to `git clone` and then remove `.git` folder? Am I missing a more obvious way of how one might end up with unprocessed sources without git repository? (except `go install`, see below)

The downside of putting things in `Makefile` is that everyone must go through it. A simple `go run` won't resolve the version, nor if you use other build tools - in fact for unrelated reasons I can't myself use `Makefile` now, I have recently switched to Nix and it has caveats that I didn't fully figure out yet, so I'm using `nix run` instead of `make run`, which goes through `flake.nix` instead of `Makefile`...

By the way one of the popular ways is to install go apps using `go install`, and I've just realized that `go install github.com/maximbaz/yubikey-touch-detector@latest` doesn't seem to fetch source tarball, so the resulting binary tries to invoke `git` :thinking: Just if you are curious to try, repro steps are below:

```sh
docker run --rm -it golang bash
apt update
apt install -y libgpgme-dev
go install github.com/maximbaz/yubikey-touch-detector@1.12.4
./bin/yubikey-touch-detector --version
```

**Comment by WhyNotHugo** [comment]
This bit of code runs when yubikey-touch-detector is executed:

https://github.com/maximbaz/yubikey-touch-detector/blob/main/main.go#L158-L162

So if you:

- Compile the binary from a git checkout
- Move the binary into `$PATH`
- `cd` anywhere outside the repository
- Run `yubikey-touch-detector`

`yubikey-touch-detector` will execute `git-describe` in that other directory, failing (or provide the wrong result).

**Comment by WhyNotHugo** [comment]
> The downside of putting things in Makefile is that everyone must go through it.

Yes, indeed. Go won't let you run custom code at compile time, so you'll need another layer that handles this.

> A simple go run won't resolve the version, nor if you use other build tools - in fact for unrelated reasons I can't myself use Makefile now, I have recently switched to Nix and it has caveats that I didn't fully figure out yet, so I'm using nix run instead of make run, which goes through flake.nix instead of Makefile...

I guess that you'd have to configure nix to run the same version injection that's done through `Makefile`? That would require replicating the same logic for each build system that you want to support.

I don't think it' feasible to make things work with `go-install`.

**Comment by maximbaz** [comment]
> yubikey-touch-detector will execute git-describe in that other directory, failing (or provide the wrong result).

Of course... :man_facepalming: Thanks for pointing this out!

**Comment by maximbaz** [comment]
> I guess that you'd have to configure nix to run the same version injection that's done through Makefile? That would require replicating the same logic for each build system that you want to support.

Well this led me down a rabbit-hole :sweat_smile: 

In fact I have a motivation somewhat similar to the one you shared in your [earlier blog post](https://whynothugo.nl/journal/2022/08/13/my-packaging-policy/) - I don't want to support _any_ build system! :smile: In the absence of `build.rs` trick like you shared for rust, I just want to give people freedom to build how ever they like.

In that regard, including a hardcoded version in the `main.go` inside the `git-archive` tarball and giving the ability for folks to override that using `-ldflags "-X main.Version=whatever"` sounds like the simplest pragmatic choice...

(I also don't want to give people potentially-outdated packaging guidelines, in the form of install targets or `CGO_*` environment variables, so I used this as an excuse to migrate to `justfile` and get rid of everything packaging-related).

**Pull request merged**
