### PR TITLE
chore: prepare gpgme for the upcoming merge

### PR DESCRIPTION
**Pull request by mochaaP**

### CODE REVIEW

**Comment by maximbaz** [comment]
Thanks! Do you want me to merge now or after the gpgme release?

**Comment by mochaaP** [comment]
I guess after the gpgme release, so we could finish removing the replace directive in one PR

**Comment by maximbaz** [comment]
Cool, just ping me when I should merge, and many thanks for keeping an eye on this!

**Comment by maximbaz** [comment]
I took the liberty to rebase your commit and merge it in https://github.com/maximbaz/yubikey-touch-detector/commit/83beabcc70f728ad40f461694862a2614d5b7782. Thanks!

**Pull request closed without merging**
