### PR TITLE
service: add libnotify service

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@archlinux.org>

### CODE REVIEW

**Comment by maximbaz** [comment]
I think we should include this in the existing service, not make a duplicate one... Because you don't want users to accidentally run both services at the same time (nothing bad will happen, but still).

How about we add `EnvironmentFile=/path/to/some/file` and then allow users to customize extra args to the binary?

**Comment by FFY00** [comment]
Yes, that makes sense.

**Comment by FFY00** [comment]
I think this approach is better, use `@` to allow users to pass arguments to the service.

**Comment by maximbaz** [comment]
It feels a bit hacky and wouldn't allow to pass two arguments (imagine someone needs to pass `-u2f-authpending-path "/new/path/to/pam-u2f-authpending"`)...

I'm grepping `svn-community` now, I can see for example `sway` is doing `EnvironmentFile=-%h/.config/sway/env`, shall we just do the same?


```
EnvironmentFile=-%h/.config/yubikey-touch-detector/service.conf
```

And actually, we can make the binary itself respect these environment variables, not to pass them via CLI arguments. In other words, we will not define `ARGS` in `service.conf`, but we will define `YUBIKEY_TOUCH_DETECTOR_LIBNOTIFY=true` and `YUBIKEY_TOUCH_DETECTOR_U2F_AUTHPENDING_PATH="/new/path/to/pam-u2f-authpending"`.

What do you think, is this going to be cleaner? If you agree, wanna implement this or should I take over? :)

**Comment by FFY00** [comment]
> It feels a bit hacky and wouldn't allow to pass two arguments (imagine someone needs to pass -u2f-authpending-path "/new/path/to/pam-u2f-authpending")...

You could actually pass several arguments:
```
yubikey-touch-detector@'--libnotify -u2f-authpending-path /new/path/to/pam-u2f-authpending'.service
```

But you are correct, it is a bit hacky. I will try to push a patch with the changes you requested.

**Comment by maximbaz** [comment]
a friendly ping @FFY00, still interested in finishing this or should I take over? :)

**Comment by FFY00** [comment]
I am interested but I have other stuff to do, you can take over :grin:.

**Comment by maximbaz** [comment]
Implemented in https://github.com/maximbaz/yubikey-touch-detector/commit/54f876ae00ea6f26bfa4a151231cf4628104a570, gonna release 1.4.0 now, let me know if you spot anything wrong with it 👍

**Pull request closed without merging**
